repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-ast
      - id: check-json
        exclude: (.devcontainer/*.json|.vscode/launch.json)
        # https://gitlab.idiap.ch/beat/beat.core/blob/master/.pre-commit-config.yaml
  - repo: https://github.com/codespell-project/codespell
    rev: v1.16.0
    hooks:
      - id: codespell
        name: codespell
        description: Checks for common misspellings in text files.
        entry: codespell README.md src/* tests/*
        language: python
        types: [text]
